replicaCount: 1

image:
  repository: rkdockerhub420/hello-world-ui
  tag: "1.0"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

service:
  type: ClusterIP
  port: 80

resources: {}

ingress:
  enabled: false

        - name: Update Helm Chart Repository
        env:
          HELM_TOKEN: ${{ secrets.HELM_REPO_TOKEN }}
          TAG: ${{ env.TAG }}
        run: |
          git clone https://x-access-token:${HELM_TOKEN}@github.com/ras-km/hello-world-helm.git
          cd hello-world-helm/hello-world

          sed -i "s/tag:.*/tag: \"${TAG}\"/" values.yaml

          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add values.yaml
          git commit -m "Update image tag to ${TAG}"

          git push

